#!/bin/bash

### CHANGE ACCORDINGLY ###
PROB="part3"
snoopyHOME="/cephfs/store/astro-hl278/nn339/hbi_project/snoopylmp"
snoopyPROJ="/cephfs/store/astro-hl278/nn339/hbi_project/snoopy-projects"
snoopyDATA="/cephfs/store/astro-hl278/nn339/hbi_project/snoopy-data"

### NO NEED TO CHANGE ###
current="${PWD}"
snoopySRC="$snoopyHOME/src"
snoopyPROB="$snoopySRC/problem/$PROB"
echo $snoopyPROB


mv $snoopyPROB/gvars.h $snoopyPROB/gvars.h.old
mv $snoopyPROB/snoopy.cfg $snoopyPROB/snoopy.cfg.old
mv $snoopySRC/initflow.c $snoopySRC/initflow.c.old
#mv $snoopySRC/spatial_conduction.c $snoopySRC/spatial_conduction.c.old

cp gvars.h snoopy.cfg ${snoopyPROB}
cp initflow.c ${snoopySRC}
#cp spatial_conduction.c ${snoopySRC}

export FFTW_DIR=export FFTPATH=/usr/local/software/spack/current/modules/maths/linux-ubuntu22.04-x86_64_v4/fftw/3.3.10/gcc/openmpi/oimqp43z  
export FFTPATH=$FFTW_DIR

### COMPILATION ###
cd ${snoopyHOME}
#./configure CC=gcc CFLAGS="-std=gnu99" LIBS="-lm" --with-problem=${PROB} --enable-openmp
./configure CC=mpicc CFLAGS="-std=gnu99" LIBS="-lm" --with-problem=${PROB} --enable-openmp --mpi=pmi2
## COMPILATION OPTIONS HERE
#cd ${snoopyHOME}
#./configure CC=mpiicc FFTPATH=${FFTW_DIR} --enable-openmp --enable-mpi --with-problem=${PROB} #actual run
#./configure CC=mpiicc --with-problem=${PROB} --enable-openmp --enable-mpi --enable-fftw-mpi 
make
make clean && make

mv $snoopyPROB/gvars.h.old $snoopyPROB/gvars.h
mv $snoopyPROB/snoopy.cfg.old $snoopyPROB/snoopy.cfg
mv $snoopySRC/initflow.c.old $snoopySRC/initflow.c
#mv $snoopySRC/spatial_conduction.c.old $snoopySRC/spatial_conduction.c

cp snoopy "$current"

### CREATE DATA DIR ###
relativePATH="${current//$snoopyPROJ/}"
mkdir -p "$snoopyDATA/$relativePATH"
mkdir -p "$snoopyDATA/$relativePATH/data"
