#!/bin/bash
#! Which partition (queue) should be used
##SBATCH -p taurus2sh
##SBATCH -w ngpu054
#SBATCH -J SNOOPY_job
#SBATCH -o job.%j.out
#SBATCH -e job.%j.err

### compute nodes
#SBATCH --nodes=1
###  MPI ranks
#SBATCH --ntasks=64
###  MPI ranks per node
#SBATCH --ntasks-per-node=64
###  tasks per MPI rank(eg OMP tasks)
#SBATCH --cpus-per-task=1

#!How much wallclock time will be required (HH:MM:SS)
#SBATCH --time=08:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=nn339@cam.ac.uk
##SBATCH --begin=now+16hours

export I_MPI_PIN_DOMAIN=4
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

srun ./snoopy
#./snoopy
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                                                                            
~                          
