#!/bin/bash
#SBATCH --job-name=SNOOPY_run
#SBATCH --output=job.%j.out
#SBATCH --error=job.%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=01:00:00

set -euo pipefail

module purge
module load gcc/9
module load openmpi/gcc/9.3/4.0.4
module load fftw-3.3.8-gcc-9.2.0-fdmsymx

module list

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_PROC_BIND=close
export OMP_PLACES=cores

srun --cpu-bind=cores ./snoopy
