#!/bin/bash
# Reset environment
module purge

# Load required modules
#module load gcc/9                         
#module load openmpi/gcc/9.3/4.0.4         
#module load fftw-3.3.8-gcc-9.2.0-fdmsymx  

module load openmpi/5.0.3/gcc/2jvxbhe6       
module load fftw/3.3.10/gcc/openmpi/oimqp43z  
 


# Set FFTW path (for convenience in compiling or running Snoopy)
export FFTPATH=/usr/local/software/spack/current/modules/maths/linux-ubuntu22.04-x86_64_v4/fftw/3.3.10/gcc/openmpi/oimqp43z  
# (Optional) Print confirmation
#echo "Modules loaded:"
#module list
#echo "FFTPATH set to: $FFTPATH"
