#!/bin/bash
#SBATCH --job-name=SNOOPY_run
#SBATCH --output=job.%j.out
#SBATCH --error=job.%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=08:00:00

module purge
module load openmpi/5.0.3/gcc/xs76solb         
module load fftw/3.3.10/gcc/openmpi/uco6ynba  

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# Force MPI to use shared memory only
export OMPI_MCA_btl=self,sm
export OMPI_MCA_btl_base_verbose=0

srun ./snoopy
