#!/bin/bash
#SBATCH --job-name=N-1.1
#SBATCH --output=job.%j.out
#SBATCH --error=job.%j.err
#SBATCH --partition=genoa-astro
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=4
#SBATCH --time=48:00:00

module purge
module load openmpi/5.0.3/gcc/2jvxbhe6
module load fftw/3.3.10/gcc/openmpi/oimqp43z

export OMP_NUM_THREADS=4

srun ./snoopy
